/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.testpoopy;

/**
 *
 * @author tobin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panel_Welcome = new javax.swing.JPanel();
        textField_Welcome_Email = new javax.swing.JTextField();
        textField_Welcome_Password = new javax.swing.JTextField();
        label_Welcome_Email = new javax.swing.JLabel();
        label_Welcome_Password = new javax.swing.JLabel();
        button_Welcome_Login = new javax.swing.JButton();
        panel_Admin = new javax.swing.JPanel();
        panel_Student = new javax.swing.JPanel();
        panel_Instructor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Welcome_Email.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        label_Welcome_Email.setText("School Email");

        label_Welcome_Password.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        label_Welcome_Password.setText("Password");

        button_Welcome_Login.setText("Log In");

        javax.swing.GroupLayout panel_WelcomeLayout = new javax.swing.GroupLayout(panel_Welcome);
        panel_Welcome.setLayout(panel_WelcomeLayout);
        panel_WelcomeLayout.setHorizontalGroup(
            panel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_WelcomeLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(panel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Welcome_Email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Welcome_Password, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_Welcome_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addGroup(panel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textField_Welcome_Email)
                        .addComponent(textField_Welcome_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        panel_WelcomeLayout.setVerticalGroup(
            panel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_WelcomeLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(panel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_Welcome_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Welcome_Email))
                .addGap(18, 18, 18)
                .addGroup(panel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_Welcome_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Welcome_Password))
                .addGap(18, 18, 18)
                .addComponent(button_Welcome_Login)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Welcome", panel_Welcome);

        javax.swing.GroupLayout panel_AdminLayout = new javax.swing.GroupLayout(panel_Admin);
        panel_Admin.setLayout(panel_AdminLayout);
        panel_AdminLayout.setHorizontalGroup(
            panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panel_AdminLayout.setVerticalGroup(
            panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Admin", panel_Admin);

        javax.swing.GroupLayout panel_StudentLayout = new javax.swing.GroupLayout(panel_Student);
        panel_Student.setLayout(panel_StudentLayout);
        panel_StudentLayout.setHorizontalGroup(
            panel_StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panel_StudentLayout.setVerticalGroup(
            panel_StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Student", panel_Student);

        javax.swing.GroupLayout panel_InstructorLayout = new javax.swing.GroupLayout(panel_Instructor);
        panel_Instructor.setLayout(panel_InstructorLayout);
        panel_InstructorLayout.setHorizontalGroup(
            panel_InstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panel_InstructorLayout.setVerticalGroup(
            panel_InstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Instructor", panel_Instructor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Welcome_Login;
    private javax.swing.JLabel label_Welcome_Email;
    private javax.swing.JLabel label_Welcome_Password;
    private javax.swing.JPanel panel_Admin;
    private javax.swing.JPanel panel_Instructor;
    private javax.swing.JPanel panel_Student;
    private javax.swing.JPanel panel_Welcome;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField textField_Welcome_Email;
    private javax.swing.JTextField textField_Welcome_Password;
    // End of variables declaration//GEN-END:variables
}
